apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
data:
  PRODUCT_SERVICE_URL: "http://product-service:20001"
  ORDER_SERVICE_URL: "http://order-service:20002"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "devops_project"