apiVersion: v1
kind: Service
metadata:
  name: order-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "20002"
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - port: 20002
      targetPort: 20002