apiVersion: v1
kind: Service
metadata:
  name: product-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "20001"
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - port: 20001
      targetPort: 20001